version: '3.7'
services:
  trino-coordinator:
    image: 'trinodb/trino:403-latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
      - '8443:443'
    volumes:
      - ./etc:/etc/trino
    networks:
      - trino-network

  opa:
    image: openpolicyagent/opa
    hostname: opa
    ports:
      - '8181:8181'
    volumes:
      - ./example.rego:/tmp/example.rego:rw
    command: 'run --server --log-level debug --server /tmp/example.rego'
    networks:
      - trino-network

  mysql:
    image: mysql:latest
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: tiny
    ports:
      - '3306:3306'
    networks:
      - trino-network
networks:
  trino-network:
    driver: bridge

